version: '3'

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    command: >
      sh -c "sleep 10 && python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_NAME=restaurant
      - DB_USER=root
      - DB_PASS=1234
      - DB_HOST=db
      - DB_PORT=3306
      - JWT_SECRET=secret
    depends_on:
      - db
  db: 
    image: mysql
    environment:
      - MYSQL_DATABASE=restaurant
      - MYSQL_ROOT_PASSWORD=1234
    ports:
      - "3306:3306"
    volumes:
      - ./db:/var/lib/mysql