# Generated by Django 4.2.6 on 2023-10-21 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_menumodel_description_menumodel_name_menumodel_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menumodel',
            name='name',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='menumodel',
            name='price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=5),
            preserve_default=False,
        ),
    ]
