# Generated by Django 4.2.6 on 2023-10-21 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_alter_restaurantmodel_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menumodel',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
