# Generated by Django 4.2.6 on 2023-10-21 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_alter_menumodel_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuvotemodel',
            name='created_at',
            field=models.DateField(auto_now_add=True),
            preserve_default=False,
        ),
    ]
