# Generated by Django 4.2.6 on 2023-10-21 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_usermodel_is_active_remove_usermodel_is_staff'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usermodel',
            table='user',
        ),
    ]
